import pytest
import sys
from pathlib import Path

# Add backend directory to sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from PIL import Image, PngImagePlugin
import numpy as np
import io

from services.metadata_cleaner_service import (
    clean_image_lossless,
    extract_image_metadata,
    clean_video_lossless,
    extract_video_metadata,
)
import subprocess
import shutil

@pytest.fixture
def sample_image_with_metadata(tmp_path: Path):
    """Creates a temporary PNG image with embedded AI metadata and PNG text chunks."""
    img_path = tmp_path / "test_ai_image.png"
    
    # Create simple RGB image
    arr = np.zeros((120, 120, 3), dtype=np.uint8)
    arr[:, :] = [128, 64, 200]
    img = Image.fromarray(arr, mode="RGB")
    
    # Add PNG text info chunks (simulating Midjourney/Stable Diffusion prompt & parameters)
    png_info = PngImagePlugin.PngInfo()
    png_info.add_text("prompt", "Hyperrealistic cinematic portrait of an astronaut, 8k")
    png_info.add_text("parameters", "Steps: 30, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 424242")
    png_info.add_text("c2pa", "manifest_signature_placeholder_jumbf")
    
    img.save(img_path, "PNG", pnginfo=png_info)
    return img_path

def test_extract_image_metadata(sample_image_with_metadata: Path):
    meta = extract_image_metadata(str(sample_image_with_metadata))
    assert meta["success"] is True
    assert meta["format"] == "PNG"
    assert meta["width"] == 120
    assert meta["height"] == 120
    assert meta["has_ai_metadata"] is True
    assert meta["embedded_prompt"] is not None
    assert "astronaut" in meta["embedded_prompt"]
    assert "prompt" in meta["png_info_chunks"]

def test_clean_image_lossless_strips_metadata(sample_image_with_metadata: Path, tmp_path: Path):
    cleaned_path = tmp_path / "test_ai_image_cleaned.png"
    res = clean_image_lossless(
        input_path=str(sample_image_with_metadata),
        output_path=str(cleaned_path),
        stealth_mode=False
    )
    
    assert res["success"] is True
    assert cleaned_path.exists()
    assert res["saved_bytes"] >= 0
    
    # Verify post-cleaning metadata
    post_meta = extract_image_metadata(str(cleaned_path))
    assert post_meta["success"] is True
    assert post_meta["embedded_prompt"] is None
    assert post_meta["c2pa_detected"] is False
    assert len(post_meta["png_info_chunks"]) == 0
    assert post_meta["has_ai_metadata"] is False

def test_clean_image_stealth_mode(sample_image_with_metadata: Path, tmp_path: Path):
    stealth_path = tmp_path / "test_ai_image_stealth.png"
    res = clean_image_lossless(
        input_path=str(sample_image_with_metadata),
        output_path=str(stealth_path),
        stealth_mode=True
    )
    
    assert res["success"] is True
    assert stealth_path.exists()
    assert res["stealth_mode"] is True
    
    # Confirm it remains openable and has exact dimensions
    with Image.open(stealth_path) as img:
        assert img.size == (120, 120)
        assert img.mode == "RGB"


@pytest.fixture
def sample_video_with_metadata(tmp_path: Path):
    """Creates a 1-second sample MP4 video with embedded AI tags and metadata."""
    vid_path = tmp_path / "test_ai_video.mp4"
    ffmpeg_bin = shutil.which("ffmpeg") or "ffmpeg"
    
    cmd = [
        ffmpeg_bin,
        "-y",
        "-f", "lavfi",
        "-i", "color=c=blue:s=320x240:d=1:r=25",
        "-c:v", "libx264",
        "-pix_fmt", "yuv420p",
        "-metadata", "title=Cinematic AI Video Scene",
        "-metadata", "comment=Generated by Runway Gen-2 AI engine",
        "-metadata", "encoder=OmniStudio AI Video Renderer",
        str(vid_path),
    ]
    subprocess.run(cmd, capture_output=True, check=True)
    return vid_path


def test_extract_video_metadata(sample_video_with_metadata: Path):
    meta = extract_video_metadata(str(sample_video_with_metadata))
    assert meta["success"] is True
    assert meta["format"] == "MP4"
    assert meta["width"] == 320
    assert meta["height"] == 240
    assert meta["fps"] == 25.0
    assert meta["duration"] >= 0.9
    assert meta["video_codec"] == "H264"
    assert meta["has_ai_metadata"] is True
    assert meta["detected_generator"] == "Runway"


def test_clean_video_lossless_strips_metadata(sample_video_with_metadata: Path, tmp_path: Path):
    cleaned_vid = tmp_path / "test_ai_video_cleaned.mp4"
    res = clean_video_lossless(
        input_path=str(sample_video_with_metadata),
        output_path=str(cleaned_vid),
        stealth_mode=False
    )
    
    assert res["success"] is True
    assert cleaned_vid.exists()
    assert res["size_after"] > 0
    
    post_meta = extract_video_metadata(str(cleaned_vid))
    assert post_meta["success"] is True
    assert post_meta["width"] == 320
    assert post_meta["height"] == 240
    assert post_meta["fps"] == 25.0
    assert post_meta["video_codec"] == "H264"
    assert post_meta["detected_generator"] is None
    assert post_meta["has_ai_metadata"] is False

