import pytest
import sys
from pathlib import Path

# Add backend directory to sys.path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from PIL import Image, PngImagePlugin
import numpy as np
import io

from services.metadata_cleaner_service import (
    clean_image_lossless,
    extract_image_metadata,
    clean_video_lossless,
    extract_video_metadata,
    clean_audio_lossless,
    extract_audio_metadata,
    inject_camera_metadata,
    inject_video_metadata,
    get_metadata_presets,
)
import subprocess
import shutil

@pytest.fixture
def sample_image_with_metadata(tmp_path: Path):
    """Creates a temporary PNG image with embedded AI metadata and PNG text chunks."""
    img_path = tmp_path / "test_ai_image.png"
    
    # Create simple RGB image
    arr = np.zeros((120, 120, 3), dtype=np.uint8)
    arr[:, :] = [128, 64, 200]
    img = Image.fromarray(arr, mode="RGB")
    
    # Add PNG text info chunks (simulating Midjourney/Stable Diffusion prompt & parameters)
    png_info = PngImagePlugin.PngInfo()
    png_info.add_text("prompt", "Hyperrealistic cinematic portrait of an astronaut, 8k")
    png_info.add_text("parameters", "Steps: 30, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 424242")
    png_info.add_text("c2pa", "manifest_signature_placeholder_jumbf")
    
    img.save(img_path, "PNG", pnginfo=png_info)
    return img_path

def test_extract_image_metadata(sample_image_with_metadata: Path):
    meta = extract_image_metadata(str(sample_image_with_metadata))
    assert meta["success"] is True
    assert meta["format"] == "PNG"
    assert meta["width"] == 120
    assert meta["height"] == 120
    assert meta["has_ai_metadata"] is True
    assert meta["embedded_prompt"] is not None
    assert "astronaut" in meta["embedded_prompt"]
    assert "prompt" in meta["png_info_chunks"]

def test_clean_image_lossless_strips_metadata(sample_image_with_metadata: Path, tmp_path: Path):
    cleaned_path = tmp_path / "test_ai_image_cleaned.png"
    res = clean_image_lossless(
        input_path=str(sample_image_with_metadata),
        output_path=str(cleaned_path),
        stealth_mode=False
    )
    
    assert res["success"] is True
    assert cleaned_path.exists()
    assert res["saved_bytes"] >= 0
    
    # Verify post-cleaning metadata
    post_meta = extract_image_metadata(str(cleaned_path))
    assert post_meta["success"] is True
    assert post_meta["embedded_prompt"] is None
    assert post_meta["c2pa_detected"] is False
    assert len(post_meta["png_info_chunks"]) == 0
    assert post_meta["has_ai_metadata"] is False

def test_clean_image_stealth_mode(sample_image_with_metadata: Path, tmp_path: Path):
    stealth_path = tmp_path / "test_ai_image_stealth.png"
    res = clean_image_lossless(
        input_path=str(sample_image_with_metadata),
        output_path=str(stealth_path),
        stealth_mode=True
    )
    
    assert res["success"] is True
    assert stealth_path.exists()
    assert res["stealth_mode"] is True
    
    # Confirm it remains openable and has exact dimensions
    with Image.open(stealth_path) as img:
        assert img.size == (120, 120)
        assert img.mode == "RGB"


@pytest.fixture
def sample_video_with_metadata(tmp_path: Path):
    """Creates a 1-second sample MP4 video with embedded AI tags and metadata."""
    vid_path = tmp_path / "test_ai_video.mp4"
    ffmpeg_bin = shutil.which("ffmpeg") or "ffmpeg"
    
    cmd = [
        ffmpeg_bin,
        "-y",
        "-f", "lavfi",
        "-i", "color=c=blue:s=320x240:d=1:r=25",
        "-c:v", "libx264",
        "-pix_fmt", "yuv420p",
        "-metadata", "title=Cinematic AI Video Scene",
        "-metadata", "comment=Generated by Runway Gen-2 AI engine",
        "-metadata", "encoder=OmniStudio AI Video Renderer",
        str(vid_path),
    ]
    subprocess.run(cmd, capture_output=True, check=True)
    return vid_path


def test_extract_video_metadata(sample_video_with_metadata: Path):
    meta = extract_video_metadata(str(sample_video_with_metadata))
    assert meta["success"] is True
    assert meta["format"] == "MP4"
    assert meta["width"] == 320
    assert meta["height"] == 240
    assert meta["fps"] == 25.0
    assert meta["duration"] >= 0.9
    assert meta["video_codec"] == "H264"
    assert meta["has_ai_metadata"] is True
    assert meta["detected_generator"] == "Runway"


def test_clean_video_lossless_strips_metadata(sample_video_with_metadata: Path, tmp_path: Path):
    cleaned_vid = tmp_path / "test_ai_video_cleaned.mp4"
    res = clean_video_lossless(
        input_path=str(sample_video_with_metadata),
        output_path=str(cleaned_vid),
        stealth_mode=False
    )
    
    assert res["success"] is True
    assert cleaned_vid.exists()
    assert res["size_after"] > 0
    
    post_meta = extract_video_metadata(str(cleaned_vid))
    assert post_meta["success"] is True
    assert post_meta["width"] == 320
    assert post_meta["height"] == 240
    assert post_meta["fps"] == 25.0
    assert post_meta["video_codec"] == "H264"
    assert post_meta["detected_generator"] is None
    assert post_meta["has_ai_metadata"] is False


@pytest.fixture
def sample_audio_with_metadata(tmp_path: Path):
    """Creates a 1-second sample MP3 audio with embedded ID3 and AI metadata."""
    aud_path = tmp_path / "test_ai_audio.mp3"
    ffmpeg_bin = shutil.which("ffmpeg") or "ffmpeg"

    cmd = [
        ffmpeg_bin,
        "-y",
        "-f", "lavfi",
        "-i", "sine=frequency=440:duration=1",
        "-c:a", "libmp3lame",
        "-metadata", "title=AI Synthesized Voice",
        "-metadata", "artist=ElevenLabs Neural Voice",
        "-metadata", "comment=Generated via Suno AI",
        str(aud_path),
    ]
    subprocess.run(cmd, capture_output=True, check=True)
    return aud_path


def test_extract_audio_metadata(sample_audio_with_metadata: Path):
    meta = extract_audio_metadata(str(sample_audio_with_metadata))
    assert meta["success"] is True
    assert meta["media_type"] == "audio"
    assert meta["format"] == "MP3"
    assert meta["duration"] >= 0.9
    assert meta["audio_codec"] == "MP3"
    assert meta["has_ai_metadata"] is True
    assert meta["detected_generator"] in ["Elevenlabs", "Suno"]
    assert meta["audio_technical"]["has_audio"] is True


def test_clean_audio_lossless_strips_metadata(sample_audio_with_metadata: Path, tmp_path: Path):
    cleaned_aud = tmp_path / "test_ai_audio_cleaned.mp3"
    res = clean_audio_lossless(
        input_path=str(sample_audio_with_metadata),
        output_path=str(cleaned_aud),
        stealth_mode=False
    )

    assert res["success"] is True
    assert cleaned_aud.exists()
    assert res["size_after"] > 0

    post_meta = extract_audio_metadata(str(cleaned_aud))
    assert post_meta["success"] is True
    assert post_meta["has_ai_metadata"] is False
    assert post_meta["detected_generator"] is None


def test_get_metadata_presets():
    presets = get_metadata_presets()
    assert presets["success"] is True
    assert "sony_a7iv" in presets["cameras"]
    assert "iphone_15_pro" in presets["cameras"]
    assert "mumbai" in presets["gps"]


def test_inject_camera_metadata(sample_image_with_metadata: Path, tmp_path: Path):
    injected_img = tmp_path / "test_camera_injected.jpg"
    res = inject_camera_metadata(
        input_path=str(sample_image_with_metadata),
        output_path=str(injected_img),
        camera_preset="sony_a7iv",
        gps_preset="mumbai",
        stealth_mode=True,
    )
    assert res["success"] is True
    assert injected_img.exists()
    assert res["verified_clean"] is True
    assert res["injected_camera"]["make"] == "Sony"
    assert res["injected_camera"]["model"] == "ILCE-7M4"
    assert res["injected_gps"]["has_gps"] is True
    assert round(res["injected_gps"]["latitude"], 2) == 19.08


def test_inject_video_metadata(sample_video_with_metadata: Path, tmp_path: Path):
    injected_vid = tmp_path / "test_video_injected.mp4"
    res = inject_video_metadata(
        input_path=str(sample_video_with_metadata),
        output_path=str(injected_vid),
        camera_preset="canon_eos_r5",
        gps_preset="delhi",
    )
    assert res["success"] is True
    assert injected_vid.exists()
    assert res["verified_clean"] is True
    assert res["injected_camera"]["make"] == "Canon"
    assert res["injected_camera"]["model"] == "Canon EOS R5"


