// Standardized AI Models Registry across all OmniStudio AI Studios & Pipelines

export interface ModelDefinition {
  id: string;
  value: string;
  label: string;
  name: string;
  provider: string;
  badge: string;
  description: string;
  category: string;
  iconType?: "openai" | "google" | "flux" | "midjourney" | "bytedance" | "custom";
  isFree?: boolean;
  active?: boolean;
  pricePerUnit?: number; // USD
}

export const IMAGE_MODELS: ModelDefinition[] = [
  {
    id: "imagen_3",
    value: "imagen_3",
    name: "Google Imagen 3",
    label: "Google Imagen 3",
    provider: "Google Cloud AI",
    badge: "PRO",
    description: "Google's flagship hyper-realistic lighting & micro-textures",
    category: "Featured models",
    iconType: "google",
    pricePerUnit: 0.030,
  },
  {
    id: "gemini_flash_image",
    value: "gemini_flash_image",
    name: "Google Gemini 2.5 Flash",
    label: "Google Gemini 2.5 Flash",
    provider: "Google DeepMind",
    badge: "FAST",
    description: "Ultra-fast high fidelity image diffusion",
    category: "Google AI",
    iconType: "google",
    pricePerUnit: 0.025,
  },
  {
    id: "gpt-image-2",
    value: "gpt-image-2",
    name: "GPT Image 2",
    label: "GPT Image 2",
    provider: "OpenAI",
    badge: "PREMIUM",
    description: "4K Images with near-perfect text rendering & skin textures",
    category: "Featured models",
    iconType: "openai",
    pricePerUnit: 0.040,
  },
  {
    id: "gpt-image-1",
    value: "gpt-image-1",
    name: "GPT Image 1 Pro",
    label: "GPT Image 1 Pro",
    provider: "OpenAI",
    badge: "PRO",
    description: "Cinema-grade visual creation & dynamic range",
    category: "Featured models",
    iconType: "openai",
    pricePerUnit: 0.035,
  },
  {
    id: "gpt-image-1-mini",
    value: "gpt-image-1-mini",
    name: "GPT Image 1 Mini",
    label: "GPT Image 1 Mini",
    provider: "OpenAI",
    badge: "FAST",
    description: "Stunning everyday images, ultra-fast generation",
    category: "Featured models",
    iconType: "openai",
    pricePerUnit: 0.020,
  },
  {
    id: "dall-e-3",
    value: "dall-e-3",
    name: "OpenAI DALL-E 3 HD",
    label: "OpenAI DALL-E 3 HD",
    provider: "OpenAI",
    badge: "HD",
    description: "High composition precision & strict prompt adherence",
    category: "OpenAI",
    iconType: "openai",
    pricePerUnit: 0.040,
  },
  {
    id: "flux_pro",
    value: "flux_pro",
    name: "Flux.1 Pro (BFL)",
    label: "Flux.1 Pro (BFL)",
    provider: "Black Forest Labs",
    badge: "SOTA",
    description: "Next-gen ultra-realistic studio typography & lighting",
    category: "Black Forest Labs",
    iconType: "flux",
    pricePerUnit: 0.050,
  },
  {
    id: "flux-schnell",
    value: "flux-schnell",
    name: "Flux.1 Schnell",
    label: "Flux.1 Schnell",
    provider: "Black Forest Labs",
    badge: "FAST",
    description: "Speed latent diffusion and rapid concept ideation",
    category: "Black Forest Labs",
    iconType: "flux",
    pricePerUnit: 0.010,
  },
  {
    id: "flux_dev",
    value: "flux_dev",
    name: "Flux.1 Dev",
    label: "Flux.1 Dev",
    provider: "Black Forest Labs",
    badge: "DEV",
    description: "Open weights high-fidelity fine-tuned guidance",
    category: "Black Forest Labs",
    iconType: "flux",
    pricePerUnit: 0.025,
  },
  {
    id: "midjourney_v6",
    value: "midjourney_v6",
    name: "Midjourney v6.1",
    label: "Midjourney v6.1",
    provider: "Midjourney",
    badge: "PRO",
    description: "Artistic contrast, cinematic mood & editorial aesthetics",
    category: "Midjourney",
    iconType: "midjourney",
    pricePerUnit: 0.045,
  },
  {
    id: "seedream_pro",
    value: "seedream_pro",
    name: "Seedream 5.0 Pro",
    label: "Seedream 5.0 Pro",
    provider: "ByteDance",
    badge: "PREMIUM",
    description: "Logically consistent images with intelligent visual reasoning",
    category: "ByteDance",
    iconType: "bytedance",
    pricePerUnit: 0.035,
  },
  {
    id: "recraft_v3",
    value: "recraft_v3",
    name: "Recraft V3",
    label: "Recraft V3",
    provider: "Graphic Studio",
    badge: "NEW",
    description: "Top-tier vector graphics, branding & graphic design",
    category: "Graphic Studio",
    iconType: "custom",
    pricePerUnit: 0.025,
  },
  {
    id: "sd_35_large",
    value: "sd_35_large",
    name: "Stable Diffusion 3.5 Large",
    label: "Stable Diffusion 3.5 Large",
    provider: "Stability AI",
    badge: "OPEN",
    description: "Open frontier multimodal prompt adherence",
    category: "Stability AI",
    iconType: "custom",
    pricePerUnit: 0.030,
  },
];

export const VIDEO_MODELS: ModelDefinition[] = [
  {
    id: "google_veo",
    value: "google_veo",
    name: "Google Veo 3.1",
    label: "Google Veo 3.1 (DeepMind)",
    provider: "Google Cloud AI",
    badge: "ACTIVE",
    description: "Cinema-grade 4K generative video by Google DeepMind",
    category: "Featured Cloud",
    iconType: "google",
    isFree: false,
    pricePerUnit: 0.60,
  },
  {
    id: "ffmpeg_local",
    value: "ffmpeg_local",
    name: "Local Ken Burns / Morph",
    label: "Local Ken Burns / Morph (FFmpeg)",
    provider: "Local Engine",
    badge: "FREE LOCAL",
    description: "Fast local GPU/CPU keyframe interpolation (100% Free)",
    category: "Hardware Engine",
    iconType: "custom",
    isFree: true,
    pricePerUnit: 0.00,
  },
  {
    id: "kling_2.0",
    value: "kling_2.0",
    name: "Kling AI 2.0 Pro",
    label: "Kling AI 2.0 Pro",
    provider: "Kuaishou AI",
    badge: "PRO",
    description: "Photorealistic physics & high dynamic kinematics",
    category: "Featured Cloud",
    iconType: "custom",
    isFree: false,
    pricePerUnit: 0.45,
  },
  {
    id: "runway_gen3",
    value: "runway_gen3",
    name: "Runway Gen-3 Alpha Turbo",
    label: "Runway Gen-3 Alpha Turbo",
    provider: "RunwayML",
    badge: "CINEMA",
    description: "Ultra-realistic cinema motion coherence & camera controls",
    category: "Featured Cloud",
    iconType: "custom",
    isFree: false,
    pricePerUnit: 0.50,
  },
  {
    id: "luma_dream",
    value: "luma_dream",
    name: "Luma Dream Machine 1.5",
    label: "Luma Dream Machine 1.5",
    provider: "Luma AI",
    badge: "CLOUD",
    description: "Consistent 3D camera parallax & fluid dynamics",
    category: "Cloud SOTA",
    iconType: "custom",
    isFree: false,
    pricePerUnit: 0.40,
  },
  {
    id: "minimax_video",
    value: "minimax_video",
    name: "MiniMax Hailuo Video-01",
    label: "MiniMax Hailuo Video-01",
    provider: "MiniMax",
    badge: "SOTA",
    description: "Cinematic resolution & natural human kinetics",
    category: "Cloud SOTA",
    iconType: "custom",
    isFree: false,
    pricePerUnit: 0.40,
  },
  {
    id: "seedance_v1",
    value: "seedance_v1",
    name: "ByteDance Seedance 1.0",
    label: "ByteDance Seedance 1.0",
    provider: "ByteDance",
    badge: "DANCE",
    description: "High-fidelity character & dance choreography",
    category: "Cloud SOTA",
    iconType: "bytedance",
    isFree: false,
    pricePerUnit: 0.35,
  },
];

export const VOICE_MODELS: ModelDefinition[] = [
  {
    id: "edge",
    value: "edge",
    name: "Microsoft Edge Neural",
    label: "Microsoft Edge Neural (Free)",
    provider: "Microsoft",
    badge: "FREE",
    description: "400+ natural neural voices, 100% free unlimited synthesis",
    category: "Neural TTS",
    iconType: "custom",
    isFree: true,
    pricePerUnit: 0.00,
  },
  {
    id: "elevenlabs",
    value: "elevenlabs",
    name: "ElevenLabs Multilingual v2",
    label: "ElevenLabs Multilingual v2",
    provider: "ElevenLabs",
    badge: "STUDIO",
    description: "Studio-grade emotional cadence & hyper-realistic speech",
    category: "Studio TTS",
    iconType: "custom",
    isFree: false,
    pricePerUnit: 0.03,
  },
];
